apiVersion: v1
kind: Service
metadata:
  name: blockchain-explorer-db
  namespace: fabric
  labels:
    run: explorer-db
spec:
  type: ClusterIP
  selector:
    name: explorer-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: pgsql
