apiVersion: v1
kind: Service
metadata:
  name: blockchain-org6peer2
  namespace: fabric
  labels:
    run: blockchain-org6peer2
spec:
  type: ClusterIP 
  selector:
    name: org6peer2
  ports:
  - protocol: TCP
    port: 30110
    name: grpc
  - protocol: TCP
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
